"""add stationery fields

Revision ID: 72b40cd3b903
Revises: 60ef7ab0ea28
Create Date: 2026-06-29 00:58:45.605718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b40cd3b903'
down_revision: Union[str, Sequence[str], None] = '60ef7ab0ea28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('unit', sa.String(), server_default='шт', nullable=False))
    op.add_column('products', sa.Column('pack_qty', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'pack_qty')
    op.drop_column('products', 'unit')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
